import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "@/styles/globals.css"
import Layout from "@/components/molecules/layout"
import ProvidersLoader from "@/components/atoms/providers"
import { AuthProvider, SidebarProvider } from "@/contexts"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Next Base",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <ProvidersLoader providers={[AuthProvider, SidebarProvider]}>
          <Layout>{children}</Layout>
        </ProvidersLoader>
      </body>
    </html>
  )
}
